from grille import Grille


def prepare_extreme1():
    grille = Grille()
    grille.assigne_case_depart(1, 8)
    grille.assigne_case_depart(2, 6)
    grille.assigne_case_depart(5, 2)
    grille.assigne_case_depart(13, 7)
    grille.assigne_case_depart(17, 5)
    grille.assigne_case_depart(18, 9)
    grille.assigne_case_depart(32, 6)
    grille.assigne_case_depart(34, 8)
    grille.assigne_case_depart(38, 4)
    grille.assigne_case_depart(48, 5)
    grille.assigne_case_depart(49, 3)
    grille.assigne_case_depart(54, 7)
    grille.assigne_case_depart(65, 2)
    grille.assigne_case_depart(75, 7)
    grille.assigne_case_depart(76, 5)
    grille.assigne_case_depart(78, 9)
    grille.assigne_case_depart(70, 6)

    return grille


def prepare_tres_difficile1():
    grille = Grille()
    grille.assigne_case_depart(3, 7)
    grille.assigne_case_depart(8, 5)
    grille.assigne_case_depart(9, 9)
    grille.assigne_case_depart(10, 4)
    grille.assigne_case_depart(11, 3)
    grille.assigne_case_depart(12, 5)
    grille.assigne_case_depart(15, 9)
    grille.assigne_case_depart(17, 8)
    grille.assigne_case_depart(20, 9)
    grille.assigne_case_depart(24, 1)
    grille.assigne_case_depart(25, 3)
    grille.assigne_case_depart(26, 4)
    grille.assigne_case_depart(30, 8)
    grille.assigne_case_depart(31, 1)
    grille.assigne_case_depart(39, 1)
    grille.assigne_case_depart(41, 9)
    grille.assigne_case_depart(43, 6)
    grille.assigne_case_depart(51, 2)
    grille.assigne_case_depart(52, 5)
    grille.assigne_case_depart(56, 6)
    grille.assigne_case_depart(57, 9)
    grille.assigne_case_depart(58, 7)
    grille.assigne_case_depart(62, 1)
    grille.assigne_case_depart(65, 1)
    grille.assigne_case_depart(67, 9)
    grille.assigne_case_depart(70, 4)
    grille.assigne_case_depart(71, 7)
    grille.assigne_case_depart(72, 5)
    grille.assigne_case_depart(73, 7)
    grille.assigne_case_depart(74, 5)
    grille.assigne_case_depart(79, 9)

    return grille


def prepare_tres_difficile2():
    grille = Grille()
    grille.assigne_case_depart(1, 9)
    grille.assigne_case_depart(2, 2)
    grille.assigne_case_depart(3, 8)
    grille.assigne_case_depart(4, 5)
    grille.assigne_case_depart(10, 7)
    grille.assigne_case_depart(11, 6)
    grille.assigne_case_depart(12, 3)
    grille.assigne_case_depart(14, 1)
    grille.assigne_case_depart(15, 8)
    grille.assigne_case_depart(17, 2)
    grille.assigne_case_depart(20, 4)
    grille.assigne_case_depart(23, 7)
    grille.assigne_case_depart(24, 2)
    grille.assigne_case_depart(27, 6)
    grille.assigne_case_depart(29, 3)
    grille.assigne_case_depart(30, 2)
    grille.assigne_case_depart(31, 8)
    grille.assigne_case_depart(40, 2)
    grille.assigne_case_depart(41, 5)
    grille.assigne_case_depart(44, 6)
    grille.assigne_case_depart(45, 3)
    grille.assigne_case_depart(46, 6)
    grille.assigne_case_depart(50, 3)
    grille.assigne_case_depart(51, 1)
    grille.assigne_case_depart(52, 2)
    grille.assigne_case_depart(55, 3)
    grille.assigne_case_depart(56, 5)
    grille.assigne_case_depart(57, 6)
    grille.assigne_case_depart(59, 8)
    grille.assigne_case_depart(62, 9)
    grille.assigne_case_depart(63, 2)
    grille.assigne_case_depart(64, 2)
    grille.assigne_case_depart(66, 4)
    grille.assigne_case_depart(70, 6)
    grille.assigne_case_depart(71, 5)
    grille.assigne_case_depart(72, 8)
    grille.assigne_case_depart(75, 9)
    grille.assigne_case_depart(76, 6)
    grille.assigne_case_depart(77, 2)
    grille.assigne_case_depart(78, 5)
    grille.assigne_case_depart(79, 4)
    grille.assigne_case_depart(80, 3)

    return grille


def prepare_difficile1():
    grille = Grille()
    grille.assigne_case_depart(3, 2)
    grille.assigne_case_depart(7, 7)
    grille.assigne_case_depart(9, 3)
    grille.assigne_case_depart(11, 3)
    grille.assigne_case_depart(15, 2)
    grille.assigne_case_depart(17, 8)
    grille.assigne_case_depart(20, 9)
    grille.assigne_case_depart(21, 1)
    grille.assigne_case_depart(22, 7)
    grille.assigne_case_depart(26, 5)
    grille.assigne_case_depart(33, 7)
    grille.assigne_case_depart(36, 8)
    grille.assigne_case_depart(37, 3)
    grille.assigne_case_depart(39, 8)
    grille.assigne_case_depart(40, 5)
    grille.assigne_case_depart(45, 4)
    grille.assigne_case_depart(46, 6)
    grille.assigne_case_depart(49, 9)
    grille.assigne_case_depart(51, 1)
    grille.assigne_case_depart(60, 3)
    grille.assigne_case_depart(61, 6)
    grille.assigne_case_depart(62, 4)
    grille.assigne_case_depart(68, 1)
    grille.assigne_case_depart(69, 8)
    grille.assigne_case_depart(72, 2)
    grille.assigne_case_depart(74, 5)

    return grille


def prepare_medium1():
    grille = Grille()
    grille.assigne_case_depart(1, 1)
    grille.assigne_case_depart(2, 5)
    grille.assigne_case_depart(4, 2)
    grille.assigne_case_depart(6, 9)
    grille.assigne_case_depart(9, 4)
    grille.assigne_case_depart(11, 4)
    grille.assigne_case_depart(15, 6)
    grille.assigne_case_depart(23, 4)
    grille.assigne_case_depart(26, 6)
    grille.assigne_case_depart(27, 3)
    grille.assigne_case_depart(29, 7)
    grille.assigne_case_depart(34, 8)
    grille.assigne_case_depart(36, 6)
    grille.assigne_case_depart(37, 6)
    grille.assigne_case_depart(45, 5)
    grille.assigne_case_depart(46, 2)
    grille.assigne_case_depart(48, 8)
    grille.assigne_case_depart(53, 1)
    grille.assigne_case_depart(55, 4)
    grille.assigne_case_depart(56, 6)
    grille.assigne_case_depart(59, 8)
    grille.assigne_case_depart(67, 6)
    grille.assigne_case_depart(71, 7)
    grille.assigne_case_depart(73, 8)
    grille.assigne_case_depart(76, 5)
    grille.assigne_case_depart(78, 1)
    grille.assigne_case_depart(80, 4)
    grille.assigne_case_depart(81, 9)

    return grille
